### ISSUE TITLE
Task-2 (Chat)

### ISSUE THREAD

**Issue by rifathossain82** [rifathossain82/Trending-Videos#5]
## Tasks

- [x] Add Sign in page.
- [x] Add User List page.
- [x] Add Chat Page.
