### ISSUE TITLE
Update Code Readability

### ISSUE THREAD

**Issue by rifathossain82** [rifathossain82/Trending-Videos#7]
## Tasks:

- [x] Remove unused code ,
- [x] Update Dashboard State Management,
- [x] Update Bottom navigation bar.
